### ISSUE TITLE
Configuration not supported anymore soon.

### ISSUE THREAD

**Issue by cris1** [rjelbert/radmon_radiation_homeassistant_integration#1]
This stops working in version 2023.12.0. Please address before upgrading.
Configuring Command Line sensor using YAML has moved.

Consult the documentation to move your YAML configuration to integration key and restart Home Assistant to fix this issue.

**Comment by mmorfey** [comment]
```
command_line:
  - sensor:
      scan_interval: 60
      name: "Radiation CPM"
      unique_id: "Radmon.org_Radiation_station_data"
      command: python -c "import requests; print(str(requests.get('https://radmon.org/radmon.php?function=lastreading&user=dittohead').text).split(' ', 1)[0])"
      unit_of_measurement: "CPM"
      value_template: "{{ value }}"
sensor:
  - platform: template
    sensors:
      radiation_sieverts:
        friendly_name: "Radiation uSv/h"
        unique_id: "Radmon.org_Radiation_station_data_sieverts"
        value_template: "{{ (states('sensor.radiation_cpm') | float(0) * 0.00812037) | round(2) }}"
        unit_of_measurement: "uSv/h"

  - platform: statistics
    name: "Radiation 30 minute average CPM"
    unique_id: "Radmon.org_Radiation_30_min_average"
    entity_id: sensor.radiation_cpm
    state_characteristic: mean
    max_age:
      minutes: 30
    sampling_size: 45

  - platform: statistics
    name: "Radiation 30 minute average uSv/h"
    unique_id: "Radmon.org_Radiation_Sieverts_30_min_average"
    entity_id: sensor.radiation_sieverts
    state_characteristic: mean
    max_age:
      minutes: 30
    sampling_size: 45
```
